# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Cater"

# The default layout to use for your application (located in
# views/layouts/main.tt)
# layout: "main" ## commented out to allow for using Template Toolkit's wrapper, defined below.

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"

session: Cookie

engines:
  template:
    template_toolkit:
      WRAPPER: layouts/main.tt
      start_tag: '[%'
      end_tag:   '%]'
  session:
    Cookie:
      secret_key: feed the people
      default_duration: 604800 # 7 days in seconds
