# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Cater"

# The default layout to use for your application (located in
# views/layouts/main.tt)
# layout: "main" ## commented out to allow for using Template Toolkit's wrapper, defined below.

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"

session: YAML

engines:
  template:
    template_toolkit:
      WRAPPER: views/layouts/main.tt
      start_tag: '[%'
      end_tag:   '%]'
  session:
    YAML:
      session_dir: ./sessions

plugins:
  Passphrase:
    default: Bcrypt
    Bcrypt:
      cost: 8
  DBIC:
    default:
      dsn: dbi:mysql:catering
      schema_class: Cater::DBSchema
      user: caterit
      password: CoMeCaTeR4Me
      options:
        RaiseError: 1
        PrintError: 1
